#! /bin/bash

aws ec2 request-spot-instances \
--availability-zone-group us-east-1f \
--spot-price 0.052 \
--type one-time \
--launch-specification \
"{ \
	\"SecurityGroupIds\": [\"sg-ba0fecca\"], \
	\"EbsOptimized\": true, \
	\"KeyName\": \"jeb-aws-keypair\", \
	\"ImageId\": \"ami-001b2b0604b8e8434\", \
	\"IamInstanceProfile\": { \
		\"Arn\": \"arn:aws:iam::803068370526:instance-profile/dev-ec2-instance\" \
	}, \
	\"InstanceType\": \"t3.xlarge\", \
	\"Placement\": { \
		\"AvailabilityZone\": \"us-east-1f\" \
	}, \
	\"UserData\": \"`base64 userdata`\" \
}"

