#! /bin/bash

aws ec2 request-spot-instances \
--availability-zone-group us-east-1f \
--spot-price 0.052 \
--type one-time \
--launch-specification \
"{ \
	\"SecurityGroupIds\": [\"sg-ba0fecca\"], \
	\"EbsOptimized\": true, \
	\"ImageId\": \"ami-0560b13623abf7d81\", \
	\"InstanceType\": \"t3.xlarge\", \
	\"Placement\": { \
		\"AvailabilityZone\": \"us-east-1f\" \
	}, \
	\"UserData\": \"`base64 userdata`\" \
}"

