#! /bin/bash

aws ec2 request-spot-instances \
--availability-zone-group us-east-1f \
--spot-price 0.052 \
--type one-time \
--launch-specification \
"{ \
	\"SecurityGroupIds\": [\"sg-ba0fecca\"], \
	\"EbsOptimized\": true, \
	\"KeyName\": \"jeb-aws-keypair\", \
	\"ImageId\": \"ami-082cdb1b1d011dfd8\", \
	\"BlockDeviceMappings\": [ \
		{ \
			\"DeviceName\": \"/dev/sda1\", \
			\"Ebs\": { \
				\"DeleteOnTermination\": true, \
				\"VolumeSize\": 32, \
				\"VolumeType\": \"gp2\" \
			} \
		} \
	], \
	\"IamInstanceProfile\": { \
		\"Arn\": \"arn:aws:iam::803068370526:instance-profile/dev-ec2-instance\" \
	}, \
	\"InstanceType\": \"t3.xlarge\", \
	\"Placement\": { \
		\"AvailabilityZone\": \"us-east-1f\" \
	}, \
	\"UserData\": \"`base64 userdata`\" \
}"

