#! /bin/bash

# dev6
# \"ImageId\": \"ami-0f04c012b77aafdfe\", \
# ubuntu 18
# \"ImageId\": \"ami-07ebfd5b3428b6f4d\", \

aws ec2 request-spot-instances \
--availability-zone-group us-east-1f \
--spot-price 0.052 \
--type one-time \
--launch-specification \
"{ \
	\"SecurityGroupIds\": [\"sg-ba0fecca\"], \
	\"EbsOptimized\": true, \
	\"ImageId\": \"ami-0f04c012b77aafdfe\", \
	\"InstanceType\": \"t3.xlarge\", \
	\"Placement\": { \
		\"AvailabilityZone\": \"us-east-1f\" \
	}, \
	\"UserData\": \"`base64 userdataold`\" \
}"

