#! /bin/bash

# TODO
# -Skype
# -cron?

if [[ $1 == "morning" ]]; then

    /usr/bin/hipchat &

    xfce4-terminal --tab --command="ssh -A cog-pair -t 'tmux att -t furtive'" --hold --tab --command="ssh -L 3001:localhost:3001 cog-pair" --hold

    google-chrome https://stapleslabs.atlassian.net/secure/RapidBoard.jspa?rapidView=18 \
    http://localhost:3001 \
    https://github.com/StaplesLabs/Magrathea \
    https://mail.google.com/mail/u/1/#inbox &

elif [[ $1 == "night" ]]; then

    pkill hipchat
    pkill chrome
    pkill ssh
    pkill xfce4-terminal
fi
