#! /bin/bash

# TODO
# -Skype
# -cron?

if [[ $1 == "morning" ]]; then

    start-work

    google-chrome https://stapleslabs.atlassian.net/secure/RapidBoard.jspa?rapidView=18 \
    http://localhost:3001 \
    https://github.com/StaplesLabs/Magrathea \
    https://mail.google.com/mail/u/1/#inbox &

elif [[ $1 == "night" ]]; then

    pkill chrome

    stop-work

fi
