#! /bin/bash

# Here's how I've used this script:
# sudo mkdir efs
# sudo chmod -R 777 efs
# run this script, to mount EFS
# sudo su
# grep efs /etc/mtab >> /etc/fstab

sudo mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport fs-a7580d26.efs.us-east-1.amazonaws.com:/ efs
